# Generated by Django 3.2.6 on 2022-05-07 10:24

import core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], default='100', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_no',
            field=models.TextField(default='00AA000000', validators=[core.validators.validate_matricno]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='part',
            field=models.CharField(choices=[('Tenor', 'Tenor'), ('Alto', 'Alto'), ('Soprano', 'Soprano'), ('HOD', 'HOD')], default='Soprano', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.IntegerField(default=1000000, validators=[core.validators.validate_regno]),
            preserve_default=False,
        ),
    ]
