# Generated by Django 3.2.6 on 2022-06-02 18:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matric_no',
            field=models.TextField(default='10AA000000', validators=[core.validators.validate_matricno]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_no',
            field=models.IntegerField(default=1000000, validators=[core.validators.validate_regno]),
        ),
    ]
