# Generated by Django 3.2.6 on 2022-05-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehearsal',
            name='category',
            field=models.CharField(choices=[('100-200', '100-200'), ('300-500', '300-500'), ('General', 'General')], max_length=100),
        ),
    ]
