# Generated by Django 3.2.6 on 2022-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('Suggested', 'Suggested'), ('Concert', 'Concert'), ('Upcoming', 'Upcoming')], max_length=100)),
                ('lyrics', models.TextField()),
            ],
        ),
    ]
